export const STATE = {
  STOPPED: 0,
  PLAYING: 1,
  PAUSED: 2,
};
export const IDX = {
  STATE: 0,
  STATE_INITIAL: 1,
  SILENCE_USEC: 2,
  CURRENT_TS: [3, 4],
  AVAILABLE_AUDIO: 5,
  AVAILABLE_VIDEO: 6,
  VIDEO_DECODER_QUEUE: 7,
  VIDEO_DECODER_LATENCY: 8,
  AUDIO_DECODER_QUEUE: 9,
  PLAYBACK_START_TS: [10, 11],
  VIDEO_LATEST_TS: [12, 13],
  AUDIO_LATEST_TS: [14, 15],
  MIN_BUFFER_SHORT: 16,
  MIN_BUFFER_LONG: 17,
  MIN_BUFFER_EMA: 18,
  CURRENT_SPEED: 19,
};
export const MODE = {
  LIVE: 0,
  VOD: 1,
};
