export const STATE = {
  STOPPED: 0,
  PLAYING: 1,
  PAUSED: 2,
};
export const IDX = {
  STATE: 0,
  SILENCE_MSEC: 1,
  CURRENT_TS: [2, 3],
  AVAILABLE_AUDIO: 4,
  VIDEO_DECODER_QUEUE: 5,
  VIDEO_DECODER_LATENCY: 6,
  AUDIO_DECODER_QUEUE: 7,
  PLAYBACK_START_TS: [8, 9],
  VIDEO_LATEST_TS: [10, 11],
};
