export const STATE = {
  STOPPED: 0,
  PLAYING: 1,
  PAUSED: 2,
};
export const IDX = {
  STATE: 0,
  SILENCE_USEC: 1,
  CURRENT_TS: [2, 3],
  AVAILABLE_AUDIO: 4,
  AVAILABLE_VIDEO: 5,
  VIDEO_DECODER_QUEUE: 6,
  VIDEO_DECODER_LATENCY: 7,
  AUDIO_DECODER_QUEUE: 8,
  PLAYBACK_START_TS: [9, 10],
  VIDEO_LATEST_TS: [11, 12],
};
